steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_ARTIFACT_REGISTRY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/portfolio:$COMMIT_SHA",
        ".",
      ]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_ARTIFACT_REGISTRY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/portfolio:$COMMIT_SHA",
      ]

  - id: "deploy prod service"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "portfolio",
        "--platform",
        "managed",
        "--region",
        "${_CLOUD_RUN_REGION}",
        "--allow-unauthenticated",
        "--image",
        "${_ARTIFACT_REGISTRY_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/portfolio:$COMMIT_SHA",
      ]

  - id: "ensure prod service live"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "services",
        "update-traffic",
        "portfolio",
        "--to-latest",
        "--platform",
        "managed",
        "--region",
        "${_CLOUD_RUN_REGION}",
      ]

substitutions:
  _ARTIFACT_REGISTRY_REGION: asia-southeast1
  _REPOSITORY: docker-images-yong-wei-portfolio
  _CLOUD_RUN_REGION: asia-southeast1

timeout: 900s
